name = "third-eye"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2025-01-01"

[vars]
VITE_GEMINI_MODEL_NAME = "gemini-2.0-flash-exp"
VITE_IMAGE_HEIGHT = "1024"
VITE_IMAGE_QUALITY_MAX = "0.9"
VITE_IMAGE_WIDTH = "1024"
VITE_REMOTE_LOGGER_BASE_URL = "https://eu-logs.ai4you.app/"
# secret - VITE_REMOTE_LOGGER_PASSWORD = "---secret---"
# secret - VITE_TALK_PASSWORD = "---secret---"
# secret - VITE_GEMINI_API_KEY = "---secret---"
# secret - VITE_EU_LOGS_API_KEY = "---secret---"
